INPUT:
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224

MODEL:
  DATASET: "med"
  META_ARCHITECTURE: "Cls"

  BACKBONE:
    CONV_BODY: "Mobile-V2"

SOLVER:
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  CHECKPOINT_PERIOD: 2000
  STEPS: (10000, 20000)
  MAX_ITER: 30100

OUTPUT_ROOT_DIR: "./result"
