INPUT:
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224

MODEL:
  DATASET: "med"
  META_ARCHITECTURE: "Cls"

  BACKBONE:
    CONV_BODY: "Mobile-V2"

  TRANSFER:
    IS_OPEN: True
    METHOD: "hidden"
    OUTPUT_NAMES: ('backbone.embed_bn', )
    WEIGHT_VALUES: (1.0, )

TRANSFER_SOLVER:
  BASE_LR: 0.001
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1000
  STEPS: (10000,)
  MAX_ITER: 15100

OUTPUT_ROOT_DIR: "./result"
