INPUT:
  MIN_SIZE_TRAIN: 224
  MAX_SIZE_TRAIN: 224

MODEL:
  DATASET: "med"
  META_ARCHITECTURE: "Cls"

  BACKBONE:
    CONV_BODY: "R-50"

SOLVER:
  BASE_LR: 0.01
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1000
  STEPS: (5000, 10000)
  MAX_ITER: 15100


OUTPUT_ROOT_DIR: "./result"
CUSTOM_OUTPUT_DIR: ""
CUSTOM_ADD_NAME: ""
